/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>;

export interface Visitors {
    date: Generated<Date>;
    id: Generated<number>;
    ip: string;
    page: string;
    user_agent: string;
}

export interface DB {
    visitors: Visitors;
}
