/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>;

export interface Account {
    id: Generated<number>;
    password: string;
    username: string;
}

export interface Article {
    content_md: string;
    created_at: Generated<Date>;
    description: string;
    id: Generated<string>;
    title: string;
    updated_at: Generated<Date>;
}

export interface ArticleEquipment {
    article_id: string;
    equipment_id: number;
    id: Generated<number>;
}

export interface Equipment {
    id: Generated<number>;
    link: string;
    name: string;
    type_id: number;
}

export interface EquipmentType {
    id: Generated<number>;
    lang_key: string;
    priority: Generated<number>;
}

export interface Exposure {
    article_id: string;
    count: number;
    date: Date;
    exposure_time_s: number;
    id: Generated<number>;
    type: string;
}

export interface GalleryImage {
    alt_text: string;
    article_id: string;
    id: Generated<number>;
    name: string;
}

export interface Visitors {
    date: Generated<Date>;
    id: Generated<number>;
    ip: string;
    page: string;
    user_agent: string;
}

export interface DB {
    account: Account;
    article: Article;
    article_equipment: ArticleEquipment;
    equipment: Equipment;
    equipment_type: EquipmentType;
    exposure: Exposure;
    gallery_image: GalleryImage;
    visitors: Visitors;
}
